routes/web.php
<?php
use Carbon\Carbon;
use App\Personnel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', 'FrontController@index')->name('home'); // this is the native homepage

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');



// Route::get('/home', 'HomeController@index');

// Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin']], function () {  //this is the native admin route

// Admin
Route::group(['prefix' => '/', 'middleware' => ['auth','admin']], function () {
    Route::get('/', 'PersonnelController@dashboard', function () {

        return view('admin.index');

    })->name('admin.index');

    Route::resource('personnel','PersonnelController');
	Route::get('officers', 'PersonnelController@officers')->name('officers');
    Route::get('enlisted', 'PersonnelController@enlisted')->name('enlisted');
    
    Route::resource('user','UserController');
});


// User
// Route::group(['prefix' => '/', 'middleware' => ['auth']], 
// 	function () {
// 	Route::get('/home', 'HomeController@index', function () {
// 		return view('user.home');
// 	})->name('user.home');

// 	Route::resource('personnel','PersonnelController');
// 	Route::get('officers', 'PersonnelController@officers')->name('officers');
// 	Route::get('enlisted', 'PersonnelController@enlisted')->name('enlisted');
// });

app/Personnel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personnel extends Model
{
    protected $fillable=['lname','fname','mname','afpsn','category','rank','status','statusDate','daysGiven','assigned','remarks','image'];

    protected $dates = [
        'created_at',
        'updated_at'
    ];

    // scoping category
    public function scopeOfficer($query)
    {
        return $query->where('category','Officer');
    }
    public function scopeEP($query)
    {
        return $query->where('category','Enlisted Personnel');
    }

    // scoping status
    public function scopeDuty($query)
    {
        return $query->where('status','duty');
    }
    public function scopeLeave($query)
    {
        return $query->where('status','leave');
    }
    public function scopeHospitalized($query)
    {
        return $query->where('status','hospitalized');
    }
    public function scopeOthers($query)
    {
        return $query->where('status','others');
    }

}

app/Http/Controllers/PersonnelController.php
<?php

namespace App\Http\Controllers;

use App\Personnel;
use Illuminate\Http\Request;
use Carbon\Carbon;

class PersonnelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $personnels=personnel::all();

        //$personnels=personnel::where('category','Officer')->get();

        // $officerOD=personnel::Officer()->Duty()->get();
        return view('admin.personnel.index', compact('personnels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.personnel.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formInput=$request->except('image');
        

        //validation
        $this->validate($request,[
            'lname'=>'required',
            'fname'=>'required',
            'mname'=>'required',
            'afpsn'=>'required',
            'category'=>'required',
            'rank'=>'required',
            'status'=>'required',
            'statusDate'=>'required',
            'assigned'=>'required',
            'remarks'=>'nullable',
            'image'=>'image|mimes:png,jpg,jpeg|max:10000'
        ]);

        // image upload
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }

        Personnel::create($formInput);
        //return redirect()->route('admin.index');
        // return back();
        return redirect()->route('personnel.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $personnel = Personnel::find($id);

        $sDate = Carbon::parse($personnel['statusDate']);
        $eDate = $sDate->addDays(7);

        return view('admin.personnel.personnel',compact('personnel','id','eDate'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $personnel=Personnel::find($id);
        return view('admin.personnel.edit',compact(['personnel']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $personnel=Personnel::find($id);

        $formInput=$request->except('image');
//        validation
        $this->validate($request,[
            'lname'=>'required',
            'fname'=>'required',
            'mname'=>'required',
            'afpsn'=>'required',
            'category'=>'required',
            'rank'=>'required',
            'status'=>'required',
            'statusDate'=>'required',
            'assigned'=>'required',
            'remarks'=>'nullable',
            'image'=>'image|mimes:png,jpg,jpeg|max:10000'
        ]);
        //        image upload
        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }
         $personnel->update($formInput);
        return redirect()->route('personnel.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Personnel::destroy($id);
        return redirect()->route('personnel.index');
    }

    // public function officersduty(){
    //     $personnels=personnel::where('rank', 'Officer');
    //     return view('admin.personnel.officersduty', compact('personnels'));
    // }

    public function officers()
    {
        $officers=personnel::Officer()->get();

        $officerOD=personnel::Officer()->Duty()->get();
        $officerOL=personnel::Officer()->Leave()->get();
        $officerOH=personnel::Officer()->Hospitalized()->get();
        $officerO=personnel::Officer()->Others()->get();
        return view('admin.personnel.officers', compact('officers','officerOD','officerOL','officerOH','officerO'));
    }

    public function enlisted()
    {
        $enlisted=personnel::EP()->get();

        $enlistedOD=personnel::EP()->Duty()->get();
        $enlistedOL=personnel::EP()->Leave()->get();
        $enlistedOH=personnel::EP()->Hospitalized()->get();
        $enlistedO=personnel::EP()->Others()->get();
        return view('admin.personnel.enlisted', compact('enlisted','enlistedOD','enlistedOL','enlistedOH','enlistedO'));
    }


    public function dashboard() {
        $dtoday = Carbon::today()->toFormattedDateString();
        $newPersonnel = personnel::orderBy('id', 'desc')->take(2)->get();
        return view('admin.index', compact('newPersonnel', 'dtoday'));
    }
}

resources/views/admin/personnel/create.blade.php
@extends('admin.layout.admin')

@section('content')

	<h3 class="content-header">Add Personnel</h3>
<hr>
		<div class="full-width">
            {!! Form::open(['route' => 'personnel.store', 'method' => 'POST', 'files' => true, 'data-parsley-validate'=>'']) !!}
			<!-- names -->
            <div class="row">
                <div class="form-group col-md-4 ">
                    {{ Form::label('lname', 'Last Name') }}
                    {{ Form::text('lname', null, array('class' => 'form-control','required'=>'','minlength'=>'2')) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('fname', 'First Name') }}
                    {{ Form::text('fname', null, array('class' => 'form-control','required'=>'','minlength'=>'3')) }}
                </div>

                <div class="form-group col-md-4">
                    {{ Form::label('mname', 'Middle Name') }}
                    {{ Form::text('mname', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
                </div>
            </div>

            <!-- AFP Info -->

            <div class="row">
                <div class="form-group col-md-4 rank-cat">
                    {{ Form::label('rank', 'Rank') }}
                    {{ Form::select('rank',
                    [ 
                        'Airman' => 'Airman',
                        'Airman Second Class' => 'Airman Second Class',
                        'Airman First Class' => 'Airman First Class',
                        'Sergeant' => 'Sergeant',
                        'Staff Sergeant' => 'Staff Sergeant',
                        'Technical Sergeant' => 'Technical Sergeant',
                        'Master Sergeant' => 'Master Sergeant',
                        'Senior Master Sergeant' => 'Senior Master Sergeant',
                        'Chief Master Sergeant' => 'Chief Master Sergeant',

                        'Secont Lieutenant' => 'Secont Lieutenant',
                        'First Lieutenant' => 'First Lieutenant',
                        'Captain' => 'Captain',
                        'Major' => 'Major',
                        'Lieutenant Colonel' => 'Lieutenant Colonel',
                        'Colonel' => 'Colonel',
                        'Brigadier General' => 'Brigadier General',
                        'Major General' => 'Major General',
                        'Lieutenant General' => 'Lieutenant General',
                        'General' => 'General'
                    ], 
                       null,
                      ['class' => 'form-control','placeholder'=>'Select Rank']) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('afpsn', 'AFP Serial Number') }}
                    
                    {{ Form::text('afpsn', null, array('class' => 'form-control','type'=>'number')) }}
                </div>
                <style type="text/css">
                    input#category {
                        cursor: none;
                        pointer-events: none;
                    }

                </style>
                <div class="form-group col-md-4">
                    {{ Form::label('category', 'Category') }}
                    {{ Form::text('category',$value=null, ['class' => 'form-control','placeholder'=>'Select Rank first','tabindex'=>'-1']) }}
                </div>
            </div>
            
            <!-- Status -->

            <div class="row">
                <div class="form-group col-md-4">
                    {{ Form::label('assigned', 'Assigned') }}
                    {{ Form::select('assigned',
                     [ 
                        'NR' => 'Not reported yet',
                        'LL' => 'LL', 
                        'VM' => 'VM',
                        'MD' => 'MD',
                        'MJ' => 'MJ',
                        'MC' => 'MP',
                        'MZ' => 'MZ'
                        
                     ],
                     null, 
                     ['class' => 'form-control']) }}
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        {{ Form::label('remarks', 'Remarks') }}
                        {{ Form::text('remarks', null, array('class' => 'form-control')) }}
                    </div>
                </div>
                
            </div>

            <div class="row">
                <div class="form-group col-md-4 stat">
                    {{ Form::label('status', 'Status') }}
                    {{ Form::select('status',
                     [ 
                        'Duty' => 'Duty', 
                        'Leave' => 'Leave',
                        'Hospitalized' => 'Hospitalized',
                        'Mission' => 'Mission',
                        'Schooling' => 'Schooling',
                        'Pass' => 'Pass',
                        'others' => 'Others'
                     ],
                     null, 
                     ['class' => 'form-control']) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('statusDate', 'Status started at') }}
                    <br>
                    {{ Form::date('statusDate', \Carbon\Carbon::now()) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('daysGiven', 'How many days?') }}
                    <br>
                    {{ Form::number('daysGiven', null, array('class' => 'form-control')) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        {{ Form::label('image', 'Image') }}
                    {{ Form::file('image',array('class' => 'form-control')) }}
                    </div>
                </div>
            </div>




             {{ Form::submit('Add Personnel', array('class' => 'btn btn-default')) }}
            {!! Form::close() !!}

        </div>

@endsection

resources/views/admin/personnel/edit.blade.php
@extends('admin.layout.admin')

@section('content')

	<h3 class="content-header">Edit Personnel</h3>
	<hr>
		<div class="full-width">
            {!! Form::model($personnel,['route' => ['personnel.update',$personnel->id], 'method' => 'PUT', 'files' => true]) !!}
			<!-- names -->
            <div class="row">
                <div class="form-group col-md-4 ">
                    {{ Form::label('lname', 'Last Name') }}
                    {{ Form::text('lname', null, array('class' => 'form-control','required'=>'','minlength'=>'2')) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('fname', 'First Name') }}
                    {{ Form::text('fname', null, array('class' => 'form-control','required'=>'','minlength'=>'3')) }}
                </div>

                <div class="form-group col-md-4">
                    {{ Form::label('mname', 'Middle Name') }}
                    {{ Form::text('mname', null, array('class' => 'form-control','required'=>'','minlength'=>'5')) }}
                </div>
            </div>

            <!-- AFP Info -->

            <div class="row">
                <div class="form-group col-md-4 rank-cat">
                    {{ Form::label('rank', 'Rank') }}
                    {{ Form::select('rank',
                    [ 
                        'Airman' => 'Airman',
                        'Airman Second Class' => 'Airman Second Class',
                        'Airman First Class' => 'Airman First Class',
                        'Sergeant' => 'Sergeant',
                        'Staff Sergeant' => 'Staff Sergeant',
                        'Technical Sergeant' => 'Technical Sergeant',
                        'Master Sergeant' => 'Master Sergeant',
                        'Senior Master Sergeant' => 'Senior Master Sergeant',
                        'Chief Master Sergeant' => 'Chief Master Sergeant',

                        'Secont Lieutenant' => 'Secont Lieutenant',
                        'First Lieutenant' => 'First Lieutenant',
                        'Captain' => 'Captain',
                        'Major' => 'Major',
                        'Lieutenant Colonel' => 'Lieutenant Colonel',
                        'Colonel' => 'Colonel',
                        'Brigadier General' => 'Brigadier General',
                        'Major General' => 'Major General',
                        'Lieutenant General' => 'Lieutenant General',
                        'General' => 'General'
                    ], 
                       null,
                      ['class' => 'form-control','placeholder'=>'Select Rank']) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('afpsn', 'AFP Serial Number') }}
                    {{ Form::text('afpsn', null, array('class' => 'form-control','type'=>'number','maxlength'=>'7')) }}
                </div>
                <style type="text/css">
                    input#category {
                        cursor: none;
                        pointer-events: none;
                    }

                </style>
                <div class="form-group col-md-4">
                    {{ Form::label('category', 'Category') }}
                    {{ Form::text('category',$value=null, ['class' => 'form-control','placeholder'=>'Select Rank first']) }}
                </div>
            </div>

            
            <!-- Status -->

            <div class="row">
                <div class="form-group col-md-4">
                    {{ Form::label('assigned', 'Assigned') }}
                    {{ Form::select('assigned',
                     [ 
                        'NR' => 'Not reported yet',
                        'LL' => 'LL', 
                        'VM' => 'VM',
                        'MD' => 'MD',
                        'MJ' => 'MJ',
                        'MC' => 'MP',
                        'MZ' => 'MZ'
                        
                     ],
                     null, 
                     ['class' => 'form-control']) }}
                </div>
                <div class="col-md-8">
                    <div class="form-group">
                        {{ Form::label('remarks', 'Remarks') }}
                        {{ Form::text('remarks', null, array('class' => 'form-control')) }}
                    </div>
                </div>
                
            </div>

            <div class="row">
                <div class="form-group col-md-4 stat">
                    {{ Form::label('status', 'Status') }}
                    {{ Form::select('status',
                     [ 
                        'Duty' => 'Duty', 
                        'Leave' => 'Leave',
                        'Hospitalized' => 'Hospitalized',
                        'Mission' => 'Mission',
                        'Schooling' => 'Schooling',
                        'Pass' => 'Pass',
                        'others' => 'Others'
                     ],
                     null, 
                     ['class' => 'form-control']) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('statusDate', 'Status started at') }}
                    <br>
                    {{ Form::date('statusDate', \Carbon\Carbon::now()) }}
                </div>
                <div class="form-group col-md-4">
                    {{ Form::label('daysGiven', 'How many days?') }}
                    <br>
                    {{ Form::number('daysGiven', null, array('class' => 'form-control')) }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        {{ Form::label('image', 'Image') }}
                    {{ Form::file('image',array('class' => 'form-control')) }}
                    </div>
                </div>
            </div>
            <hr>
            <a href="{{url()->previous()}}" class="btn btn-default">Cancel</a>
             {{ Form::submit('Done', array('class' => 'btn btn-default')) }}
            {!! Form::close() !!}

        </div>

@endsection

resources/views/admin/personnel/enlisted.blade.php
@extends('admin.layout.admin')

@section('content')
<h3 class="text-center content-header">List of Enlisted Personnels</h3>
<hr>
<!-- personnels called from personnel controller -->

<table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
  <tr>
    <!-- <th>ID</th> -->
    <th>Rank</th>
    <!-- <th>Last Name</th> 
    <th>First Name</th>
    <th>Middle Name</th> -->
    <th>Name</th> 
    <th>AFP Serial No.</th> 
    <th>Assigned</th> 
    <th>Status</th>
    <th>Status started at</th>
    <th>Remarks</th>
    <th>Action</th>
    <!-- <th>Image</th> -->
  </tr>
  @forelse($enlisted as $ep) 
  <tr>
    <!-- <td>{{$ep->id}}</td> -->
    <td>{{$ep->rank}}</td>
    <!-- <td>{{$ep->lname}}</td> 
    <td>{{$ep->fname}}</td>
    <td>{{$ep->mname}}</td> -->
    <td>{{$ep->lname}}, {{$ep->fname}} {{$ep->mname}}</td>
    <td>{{$ep->afpsn}}</td> 
    <td>{{$ep->assigned}}</td>
    <td>{{$ep->status}}</td>
    <td>{{$ep->statusDate}}</td>
    <td>{{$ep->remarks}}</td> 
    <!-- <td><img src="{{url('images',$ep->image)}}" alt="2x2" width="96" height="96" /></td>  -->
    <td>
        <a href="{{route('personnel.edit',$ep->id)}}" >Edit</a>
        |
        <a href="{{action('PersonnelController@show', $ep['id'])}}">View</a>
    </td> 
  </tr>
  @empty
    <h3>No Personnel</h3>
  @endforelse
</table>

<hr>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#home">Recap</a></li>
  <li><a data-toggle="tab" href="#duty">On Duty</a></li>
  <li><a data-toggle="tab" href="#leave">On Leave</a></li>
  <li><a data-toggle="tab" href="#hospitalized">Hospitalized</a></li>
  <li><a data-toggle="tab" href="#others">Others</a></li>
</ul>

<div class="tab-content">
  <div id="home" class="tab-pane fade in active">
    <table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
      <tr>
        <th><b>On Duty</b></th>
        <th><b>On Leave</b></th>
        <th><b>Hospitalized</b></th>
        <th><b>Others</b></th>
      </tr>
      <tr>
        <td>{{count($enlistedOD)}}</td>
        <td>{{count($enlistedOL)}}</td>
        <td>{{count($enlistedOH)}}</td>
        <td>{{count($enlistedO)}}</td>
      </tr>
    </table>
  </div>
  <div id="duty" class="tab-pane fade">
    <table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
      <tr>
        <th>Rank</th>
        <th>Last Name</th> 
        <th>First Name</th>
        <th>Middle Name</th>
        <th>AFP Serial No.</th> 
        <th>Assigned</th> 
        <th>Remarks</th>
        <!-- <th>Image</th> -->
      </tr>
      @forelse($enlistedOD as $enlisted) 
      <tr>
        <td>{{$enlisted->rank}}</td>
        <td>{{$enlisted->lname}}</td> 
        <td>{{$enlisted->fname}}</td>
        <td>{{$enlisted->mname}}</td>
        <td>{{$enlisted->afpsn}}</td> 
        <td>{{$enlisted->assigned}}</td>
        <td>{{$enlisted->remarks}}</td> 
      </tr>
      @empty
        <h3>No Personnel On Duty</h3>
      @endforelse
    </table>
  </div>
  <div id="leave" class="tab-pane fade">
    <table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
      <tr>
        <th>Rank</th>
        <th>Last Name</th> 
        <th>First Name</th>
        <th>Middle Name</th>
        <th>AFP Serial No.</th> 
        <th>Assigned</th> 
        <th>Remarks</th>
        <!-- <th>Image</th> -->
      </tr>
      @forelse($enlistedOL as $enlisted) 
      <tr>
        <td>{{$enlisted->rank}}</td>
        <td>{{$enlisted->lname}}</td> 
        <td>{{$enlisted->fname}}</td>
        <td>{{$enlisted->mname}}</td>
        <td>{{$enlisted->afpsn}}</td> 
        <td>{{$enlisted->assigned}}</td>
        <td>{{$enlisted->remarks}}</td> 
      </tr>
      @empty
        <h3>No Personnel On Leave</h3>
      @endforelse
    </table>
  </div>
  <div id="hospitalized" class="tab-pane fade">
    <table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
      <tr>
        <th>Rank</th>
        <th>Last Name</th> 
        <th>First Name</th>
        <th>Middle Name</th>
        <th>AFP Serial No.</th> 
        <th>Assigned</th> 
        <th>Remarks</th>
        <!-- <th>Image</th> -->
      </tr>
      @forelse($enlistedOH as $enlisted) 
      <tr>
        <td>{{$enlisted->rank}}</td>
        <td>{{$enlisted->lname}}</td> 
        <td>{{$enlisted->fname}}</td>
        <td>{{$enlisted->mname}}</td>
        <td>{{$enlisted->afpsn}}</td> 
        <td>{{$enlisted->assigned}}</td>
        <td>{{$enlisted->remarks}}</td> 
      </tr>
      @empty
        <h3>No Personnel Hospitalized</h3>
      @endforelse
    </table>
  </div>
  <div id="others" class="tab-pane fade">
    <table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
      <tr>
        <th>Rank</th>
        <th>Last Name</th> 
        <th>First Name</th>
        <th>Middle Name</th>
        <th>AFP Serial No.</th> 
        <th>Assigned</th> 
        <th>Remarks</th>
        <!-- <th>Image</th> -->
      </tr>
      @forelse($enlistedO as $enlisted) 
      <tr>
        <td>{{$enlisted->rank}}</td>
        <td>{{$enlisted->lname}}</td> 
        <td>{{$enlisted->fname}}</td>
        <td>{{$enlisted->mname}}</td>
        <td>{{$enlisted->afpsn}}</td> 
        <td>{{$enlisted->assigned}}</td>
        <td>{{$enlisted->remarks}}</td> 
      </tr>
      @empty
        <h3>No Personnel</h3>
      @endforelse
    </table>
  </div>
</div>
@endsection

resources/views/admin/personnel/index.blade.php
@extends('admin.layout.admin')

@section('content')

<h3 class="text-center content-header">List of Personnel</h3>
<hr>
<a href="{{route('personnel.create')}}" class="btn btn-primary btn-add">
    <i class="fas fa-plus"></i> Add Personnel
</a>
<a href="#" class="btn btn-primary btn-add">
    <i class="fas fa-plus"></i> Add Civilian Employee
</a>
<!-- personnels called from personnel controller -->

<table id="personnel-list" style="width:100%" class="text-left table table-striped table-bordered">
  <tr>
    <!-- <th>ID</th> -->
    <th>Rank</th>
    <!-- <th>Last Name</th> 
    <th>First Name</th>
    <th>Middle Name</th> -->
    <th>Name</th>
    <th>AFP Serial No.</th> 
    <th>Assigned</th> 
    <th>Status</th>
    <th>Status started at</th>
    <th>Remarks</th>
    <th>Action</th>
    <!-- <th>Image</th> -->
  </tr>
  @forelse($personnels as $personnel) 
  <tr>
    <!-- <td>{{$personnel->id}}</td> -->
    <td>{{$personnel->rank}}</td>
    <!-- <td>{{$personnel->lname}}</td> 
    <td>{{$personnel->fname}}</td>
    <td>{{$personnel->mname}}</td> -->
    <td>{{$personnel->lname}}, {{$personnel->fname}} {{$personnel->mname}}</td>
    <td>{{$personnel->afpsn}}</td> 
    <td>{{$personnel->assigned}}</td>
    <td>{{$personnel->status}}</td>
    <td>{{$personnel->statusDate}}</td>
    <td>{{$personnel->remarks}}</td> 
    <!-- <td><img src="{{url('images',$personnel->image)}}" alt="2x2" width="96" height="96" /></td>  -->
    <td>
        <a href="{{route('personnel.edit',$personnel->id)}}" >Edit</a>
        |
        <a href="{{action('PersonnelController@show', $personnel['id'])}}">View</a>
    </td> 
  </tr>
  @empty
    <h3>No Personnel</h3>
  @endforelse
</table>




<!-- ------------------------------- -->

@endsection

resources/views/admin/personnel/personnel.blade.php
@extends('admin.layout.admin')

@section('content')




<div id="personnel-indvl" class="row">
  <div class=" col-md-6 col-md-offset-3 ">
    <div class="thumbnail text-center">
    <p><b>AFP Serial No: {{$personnel->afpsn}}</b></p>
    <img src="{{url('images',$personnel->image)}}" alt="2x2" width="200" height="100" />
    <hr>
    <p><strong>{{$personnel->lname}}, {{$personnel->fname}} {{$personnel->mname}}</strong></p>
    <hr>
    <p>{{$personnel->rank}}</p>
    <hr>
    <p><b>Designation</b> <br> {{$personnel->assigned}}</p>
    <p><b>Status</b> <br> {{$personnel->status}}</p>
    <p><b>{{$personnel->status}} Started at</b> <br> {{$personnel->statusDate}}</p>
    <p><b>Remarks</b> <br> {{$personnel->remarks}}</p>
    <hr>
    
    <div class="action">
        <a href="{{route('personnel.edit',$personnel->id)}}" class="edit-btn">Edit</a>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del-btn">
          Delete
        </button>

    </div>

    <!-- spacer -->
    <br>

    <strong>{{$eDate}}</strong>
  </div>   
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="del-btn" tabindex="-1" role="dialog" aria-labelledby="hayme" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h4>Are you sure you want to remove this Personnel?</h4>
      </div>
      <div class="modal-footer">
        <form action="{{route('personnel.destroy',$personnel->id)}}"  method="POST">
            {{csrf_field()}}
            {{method_field('DELETE')}}
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
@endsection