routes/web.php
<?php
use Carbon\Carbon;
use App\Personnel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', 'FrontController@index')->name('home'); // this is the native homepage

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');



// Route::get('/home', 'HomeController@index');

// Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin']], function () {  //this is the native admin route

// Admin
Route::group(['prefix' => '/', 'middleware' => ['auth','admin']], function () {
    Route::get('/', 'PersonnelController@dashboard', function () {

        return view('admin.index');

    })->name('admin.index');

    Route::resource('personnel','PersonnelController');
	Route::get('officers', 'PersonnelController@officers')->name('officers');
    Route::get('enlisted', 'PersonnelController@enlisted')->name('enlisted');
    
    Route::resource('user','UserController');
});


// User
// Route::group(['prefix' => '/', 'middleware' => ['auth']], 
// 	function () {
// 	Route::get('/home', 'HomeController@index', function () {
// 		return view('user.home');
// 	})->name('user.home');

// 	Route::resource('personnel','PersonnelController');
// 	Route::get('officers', 'PersonnelController@officers')->name('officers');
// 	Route::get('enlisted', 'PersonnelController@enlisted')->name('enlisted');
// });

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function isAdmin()
    {
        return $this->admin;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Carbon\Carbon;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=user::all();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/home.blade.php
@extends('layouts.app')

@section('content')
<!--@if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif -->

<div class="container">
    <h1>Welcome back <b>{{ Auth::user()->name }}</b></h1>
    <hr>
    
<h3 class="text-center content-header">List of Personnel</h3>
<hr>
<a href="#" class="btn btn-primary btn-add">
    <i class="fas fa-plus"></i> Add Personnel
</a>
<!-- personnels called from personnel controller -->

<table id="personnel-list" style="margin-top: 20px; width:100%" class="text-left table table-striped table-bordered">
  <tr>
    <!-- <th>ID</th> -->
    <th>Rank</th>
    <th>Last Name</th> 
    <th>First Name</th>
    <th>Middle Name</th>
    <th>AFP Serial No.</th> 
    <th>Assigned</th> 
    <th>Status</th>
    <th>Status started at</th>
    <th>Remarks</th>
    <th>Action</th>
    <!-- <th>Image</th> -->
  </tr>
  @forelse($personnels as $personnel) 
  <tr>
    <!-- <td>{{$personnel->id}}</td> -->
    <td>{{$personnel->rank}}</td>
    <td>{{$personnel->lname}}</td> 
    <td>{{$personnel->fname}}</td>
    <td>{{$personnel->mname}}</td>
    <td>{{$personnel->afpsn}}</td> 
    <td>{{$personnel->assigned}}</td>
    <td>{{$personnel->status}}</td>
    <td>{{$personnel->statusDate}}</td>
    <td>{{$personnel->remarks}}</td> 
    <!-- <td><img src="{{url('images',$personnel->image)}}" alt="2x2" width="96" height="96" /></td>  -->
    <td>
        <a href="{{route('personnel.edit',$personnel->id)}}" >Edit</a>
        |
        <a href="{{action('PersonnelController@show', $personnel['id'])}}">View</a>
    </td> 
  </tr>
  @empty
    <h3>No Personnel</h3>
  @endforelse
</table>
</div>
@endsection