routes/web.php
<?php
use Carbon\Carbon;
use App\Personnel;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Route::get('/', 'FrontController@index')->name('home'); // this is the native homepage

Auth::routes();

Route::get('/logout', 'Auth\LoginController@logout');



// Route::get('/home', 'HomeController@index');

// Route::group(['prefix' => 'admin', 'middleware' => ['auth','admin']], function () {  //this is the native admin route

// Admin
Route::group(['prefix' => '/', 'middleware' => ['auth','admin']], function () {
    Route::get('/', 'PersonnelController@dashboard', function () {

        return view('admin.index');

    })->name('admin.index');

    Route::resource('personnel','PersonnelController');
	Route::get('officers', 'PersonnelController@officers')->name('officers');
    Route::get('enlisted', 'PersonnelController@enlisted')->name('enlisted');
    
    Route::resource('user','UserController');
});


// User
// Route::group(['prefix' => '/', 'middleware' => ['auth']], 
// 	function () {
// 	Route::get('/home', 'HomeController@index', function () {
// 		return view('user.home');
// 	})->name('user.home');

// 	Route::resource('personnel','PersonnelController');
// 	Route::get('officers', 'PersonnelController@officers')->name('officers');
// 	Route::get('enlisted', 'PersonnelController@enlisted')->name('enlisted');
// });

resources/views/admin/layout/includes/header.blade.php
<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <!-- Logo -->
                <div class="logo">
                    <a href="{{route('admin.index')}}">
                        <img src="{{asset('images/logo.png')}}" alt="Alternate Text" />205th Tactical Helicopter Wing
                    </a>
                </div>
            </div>

            <div class="col-md-2 pull-right">
                <div class="navbar navbar-inverse" role="banner">
                    <nav class="collapse navbar-collapse bs-navbar-collapse navbar-right" role="navigation">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    {{Auth::user()['name']}}
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu animated fadeInUp">
                                    <!-- <li><a href="{{url('/')}}">Front End</a></li> -->
                                    <li><a href="{{url('/logout')}}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/admin/layout/includes/sidenav.blade.php
{{-- Side Navigation --}}

<div class="sidebar content-box" style="display: block;">
    <ul class="nav">
        <!-- Main menu -->
        <li class="current"><a href="{{route('admin.index')}}"><i class="glyphicon glyphicon-home"></i>
                Dashboard</a></li>
        <li class="submenu">
            <a href="#">
                <i class="fas fa-fighter-jet"></i> Personnel
                <span class="caret pull-right"></span>
            </a>
            <!-- Sub menu -->
            <ul>
                <li>
                    <a href="{{route('personnel.index')}}">View All</a>
                </li>
                <li>
                    <a href="{{route('officers')}}">Officers</a>
                </li>

                <li>
                    <a href="{{route('enlisted')}}">Enlisted Personnels</a>
                </li>

                <li>
                    <a href="#">Civilian Employees</a>
                </li>
            </ul>
        </li>
        @if(Auth::user()->isAdmin())
        <li class="submenu">
            <a href="#">
                <i class="fas fa-user"></i> Users
                <span class="caret pull-right"></span>
            </a>
            <!-- Sub menu -->
            <ul>
                <li>
                    <a href="{{route('user.index')}}">All Users</a>
                </li>
                <li>
                    <a href="#">Add Users</a>
                </li>
            </ul>
        </li>
        @else
            
        @endif
    </ul>
</div>
 <!-- ADMIN SIDE NAV-->